// Default site settings
export const defaultSettings = {
  site_name: 'OpenClaw大龙虾',
  site_tagline: '从零开始的 AI 助手搭建指南',
  primary_color: '#61177c',
  accent_color: '#b92d5d'
}

// Default resources - FULL DATA (186 items)
export const defaultResources = [
  { id: 154, title: 'OpenClaw 官方文档', description: '完整 API 参考', url: 'https://docs.openclaw.ai', category: '官方资源', lang: '中文', source: 'OpenClaw', starred: 1 },
  { id: 155, title: 'GitHub openclaw/openclaw', description: '源代码 (279k+ ⭐)', url: 'https://github.com/openclaw/openclaw', category: '官方资源', lang: 'EN', source: 'GitHub', starred: 1 },
  { id: 156, title: 'ClawHub 技能市场', description: '发现和安装 AI 技能插件', url: 'https://clawhub.com', category: '官方资源', lang: 'EN', source: 'ClawHub', starred: 1 },
  { id: 157, title: '飞书7天入门知识库', description: '系统化学习路径', url: 'https://my.feishu.cn/wiki/YkWgwqSchi9xW3kEuZscAm0lnFf', category: '官方资源', lang: '中文', source: 'OpenClaw 101', starred: 1 },
  { id: 158, title: '阿里云 部署 OpenClaw 构建钉钉', description: '轻量应用服务器一键部署', url: 'https://help.aliyun.com', category: '云平台部署', lang: '中文', source: '阿里云', starred: 1 },
  { id: 159, title: '腾讯云 接入飞书教程', description: 'Lighthouse 一键部署', url: 'https://cloud.tencent.com', category: '云平台部署', lang: '中文', source: '腾讯云', starred: 1 },
  { id: 160, title: 'DigitalOcean One-Click Deploy', description: 'DigitalOcean 一键部署', url: 'https://www.digitalocean.com', category: '云平台部署', lang: 'EN', source: 'DigitalOcean', starred: 0 },
  { id: 161, title: 'OpenClaw 下载安装使用教程', description: '系统要求、安装方式对比', url: 'https://apifox.com', category: '入门部署', lang: '中文', source: 'Apifox', starred: 1 },
  { id: 162, title: '菜鸟教程 OpenClaw 完整教程', description: '从 git clone 到 pnpm build', url: 'https://www.runoob.com', category: '入门部署', lang: '中文', source: '菜鸟教程', starred: 1 },
  { id: 163, title: '搬主题 一键安装部署', description: '钉钉/飞书/微信/Web四种集成', url: 'https://www.banzhuti.com', category: '入门部署', lang: '中文', source: '搬主题', starred: 1 },
  { id: 164, title: 'DataCamp OpenClaw Tutorial', description: 'WhatsApp 远程控制教程', url: 'https://www.datacamp.com', category: '入门部署', lang: 'EN', source: 'DataCamp', starred: 1 },
  { id: 165, title: 'freeCodeCamp OpenClaw Full Tutorial', description: '从被动聊天到主动 Agent', url: 'https://www.freecodecamp.org', category: '入门部署', lang: 'EN', source: 'freeCodeCamp', starred: 1 },
  { id: 166, title: 'WiTechPedia Complete Guide', description: 'Windows/macOS/Linux 全平台', url: 'https://www.witechpedia.com', category: '入门部署', lang: 'EN', source: 'WiTechPedia', starred: 0 },
  { id: 167, title: 'Zilliz Install OpenClaw on Mac', description: 'macOS 部署指南', url: 'https://medium.com', category: '入门部署', lang: 'EN', source: 'Medium', starred: 0 },
  { id: 168, title: 'Towards Data Science', description: '权威数据科学媒体', url: 'https://towardsdatascience.com', category: '入门部署', lang: 'EN', source: 'TDS', starred: 0 },
  { id: 169, title: 'CSDN OpenClaw开源汉化版', description: '完全汉化版部署指南', url: 'https://blog.csdn.net', category: '入门部署', lang: '中文', source: 'CSDN', starred: 1 },
  { id: 170, title: 'Apidog How to Update OpenClaw', description: '工程导向的更新指南', url: 'https://apidog.com', category: '入门部署', lang: 'EN', source: 'Apidog', starred: 0 },
  { id: 171, title: 'The Neuron AI', description: 'QMD 记忆后端配置', url: 'https://www.theneuron.ai', category: '入门部署', lang: 'EN', source: 'The Neuron AI', starred: 0 },
  { id: 172, title: 'Raspberry Pi 部署 OpenClaw', description: '将树莓派变成 AI Agent', url: 'https://www.raspberrypi.com', category: '入门部署', lang: 'EN', source: 'Raspberry Pi', starred: 1 },
  { id: 173, title: '博客园 安装 OpenClaw 对接飞书', description: 'Windows 系统保姆级', url: 'https://www.cnblogs.com', category: '入门部署', lang: '中文', source: '博客园', starred: 0 },
  { id: 174, title: '知乎 2026年新手部署教程', description: '阿里云生态下超详细', url: 'https://zhuanlan.zhihu.com', category: '入门部署', lang: '中文', source: '知乎', starred: 0 },
  { id: 175, title: '掘金 OpenClaw 安装教程', description: '完整记录，含架构理解', url: 'https://juejin.cn', category: '入门部署', lang: '中文', source: '掘金', starred: 0 },
  { id: 176, title: 'DEV Community OpenClaw Setup', description: 'Jetson/Mac Mini/Raspberry Pi', url: 'https://dev.to', category: '入门部署', lang: 'EN', source: 'DEV', starred: 0 },
  { id: 177, title: 'Medium Mastering OpenClaw', description: '自定义 Skills，安全加固', url: 'https://medium.com', category: '入门部署', lang: 'EN', source: 'Medium', starred: 0 },
  { id: 178, title: 'Open-Claw.org Ultimate Guide', description: 'Docker 和 Node.js 部署', url: 'https://open-claw.org', category: '入门部署', lang: 'EN', source: 'Open-Claw.org', starred: 0 },
  { id: 179, title: 'Foxes Sell Faster Tutorial', description: '零命令行基础教程', url: 'https://www.foxessellfaster.com', category: '入门部署', lang: 'EN', source: 'Foxes Sell Faster', starred: 0 },
  { id: 180, title: 'heyuan110.com 超详细上手', description: '小白友好 + 老鸟技巧', url: 'https://www.heyuan110.com', category: '入门部署', lang: '中文', source: 'heyuan110', starred: 0 },
  { id: 181, title: 'CSDN 251000字完整教程', description: '16章正文 + 66个案例', url: 'https://blog.csdn.net', category: '入门部署', lang: '中文', source: 'CSDN', starred: 0 },
  { id: 182, title: 'Reddit Ultimate Setup', description: 'Reddit 社区指南', url: 'https://www.reddit.com', category: '入门部署', lang: 'EN', source: 'Reddit', starred: 0 },
  { id: 183, title: 'PromptLayer Step-by-Step', description: 'Agentic AI 团队出品', url: 'https://blog.promptlayer.com', category: '入门部署', lang: 'EN', source: 'PromptLayer', starred: 0 },
  { id: 184, title: 'Robo Rhythms Beginner Guide', description: '常见陷阱如上下文丢失', url: 'https://www.roborhythms.com', category: '入门部署', lang: 'EN', source: 'Robo Rhythms', starred: 0 },
  { id: 185, title: 'AlphaTechFinance 完整指南', description: '本地 AI Agent、用例与安全', url: 'https://alphatechfinance.com', category: '入门部署', lang: 'EN', source: 'AlphaTechFinance', starred: 0 },
  { id: 186, title: 'Adven Boost 10 Steps', description: 'Structured 10-step playbook', url: 'https://advenboost.com', category: '入门部署', lang: 'EN', source: 'Adven Boost', starred: 0 },
  { id: 187, title: 'BoostedHost Install OpenClaw', description: 'Plain language guide', url: 'https://boostedhost.com', category: '入门部署', lang: 'EN', source: 'BoostedHost', starred: 0 },
  { id: 188, title: 'Creator Economy Master', description: '5 real use cases', url: 'https://creatoreconomy.so', category: '入门部署', lang: 'EN', source: 'Creator Economy', starred: 0 },
  { id: 189, title: 'Turing College', description: '三大核心能力解析', url: 'https://www.turingcollege.com', category: '入门部署', lang: 'EN', source: 'Turing College', starred: 0 },
  { id: 190, title: 'Contabo Self-Hosted Guide', description: 'VPS 托管指南', url: 'https://contabo.com', category: '入门部署', lang: 'EN', source: 'Contabo', starred: 0 },
  { id: 191, title: 'SitePoint Mac Mini', description: 'Mac Mini 本地部署', url: 'https://www.sitepoint.com', category: '入门部署', lang: 'EN', source: 'SitePoint', starred: 0 },
  { id: 192, title: 'Latenode What is OpenClaw', description: '100+ 技能可用', url: 'https://latenode.com', category: '入门部署', lang: 'EN', source: 'Latenode', starred: 0 },
  { id: 193, title: 'WIRED I Loved My OpenClaw', description: '深度报道：魅力与风险', url: 'https://www.wired.com', category: '入门部署', lang: 'EN', source: 'WIRED', starred: 0 },
  { id: 194, title: 'Fortune Security Experts', description: '新型安全风险', url: 'https://fortune.com', category: '入门部署', lang: 'EN', source: 'Fortune', starred: 0 },
  { id: 195, title: 'ZDNet From Clawdbot', description: '34 个安全 commit', url: 'https://www.zdnet.com', category: '入门部署', lang: 'EN', source: 'ZDNet', starred: 0 },
  { id: 196, title: 'Forward Future 25+ Use Cases', description: '41 页 PDF，真实案例集', url: 'https://www.forwardfuture.ai', category: '玩法与场景', lang: 'EN', source: 'Forward Future', starred: 0 },
  { id: 197, title: 'TechStartups 35 Ways', description: '最热门的 35 种自动化', url: 'https://techstartups.com', category: '玩法与场景', lang: 'EN', source: 'TechStartups', starred: 0 },
  { id: 198, title: '飞书 部署教程', description: '飞书机器人配置', url: 'https://www.feishu.cn', category: '平台接入', lang: '中文', source: '飞书', starred: 1 },
  { id: 199, title: '钉钉 部署教程', description: '钉钉机器人配置', url: 'https://www.dingtalk.com', category: '平台接入', lang: '中文', source: '钉钉', starred: 0 },
  { id: 200, title: 'Telegram Bot 配置', description: 'Telegram Bot 完整配置', url: 'https://core.telegram.org', category: '平台接入', lang: 'EN', source: 'Telegram', starred: 0 },
  { id: 201, title: 'Discord Bot 配置', description: 'Discord Bot 部署', url: 'https://discord.com', category: '平台接入', lang: 'EN', source: 'Discord', starred: 0 },
  { id: 202, title: 'WhatsApp 连接电脑', description: 'WhatsApp Business API', url: 'https://www.whatsapp.com', category: '平台接入', lang: 'EN', source: 'WhatsApp', starred: 0 },
  { id: 203, title: 'Signal 隐私通讯', description: 'Signal Bot 配置', url: 'https://signal.org', category: '平台接入', lang: 'EN', source: 'Signal', starred: 0 },
  { id: 204, title: 'Slack 工作通讯', description: 'Slack Bot 集成', url: 'https://api.slack.com', category: '平台接入', lang: 'EN', source: 'Slack', starred: 0 },
  { id: 205, title: '微信 企业微信', description: '微信机器人配置', url: 'https://work.weixin.qq.com', category: '平台接入', lang: '中文', source: '微信', starred: 0 },
  { id: 206, title: 'Twitter Bot 配置', description: 'Twitter API 集成', url: 'https://developer.twitter.com', category: '平台接入', lang: 'EN', source: 'Twitter', starred: 0 },
  { id: 207, title: '飞书开放平台', description: '飞书应用开发文档', url: 'https://open.feishu.cn', category: '平台接入', lang: '中文', source: '飞书', starred: 0 },
  { id: 208, title: '钉钉开放平台', description: '钉钉应用开发文档', url: 'https://developers.dingtalk.com', category: '平台接入', lang: '中文', source: '钉钉', starred: 0 },
  { id: 209, title: 'WebChat 网页聊天', description: '直接网页访问', url: 'https://docs.openclaw.ai', category: '平台接入', lang: 'EN', source: 'OpenClaw', starred: 0 },
  { id: 210, title: 'Browser Relay 浏览器控制', description: '浏览器扩展控制', url: 'https://github.com', category: '平台接入', lang: 'EN', source: 'GitHub', starred: 0 },
  { id: 211, title: 'Terminal 终端界面', description: '终端直接交互', url: 'https://docs.openclaw.ai', category: '平台接入', lang: 'EN', source: 'OpenClaw', starred: 0 },
  { id: 212, title: 'B站 OpenClaw 海量全玩法', description: '国内网络使用 + 本地部署', url: 'https://www.bilibili.com', category: '视频教程', lang: '中文', source: 'Bilibili', starred: 1 },
  { id: 213, title: 'B站 本地部署接入四平台', description: '10分钟保姆级', url: 'https://www.bilibili.com', category: '视频教程', lang: '中文', source: 'Bilibili', starred: 0 },
  { id: 214, title: 'YouTube Full Setup Tutorial', description: 'Complete walkthrough', url: 'https://www.youtube.com', category: '视频教程', lang: 'EN', source: 'YouTube', starred: 0 },
  { id: 215, title: 'YouTube Tutorial for Beginners', description: 'Comprehensive course', url: 'https://www.youtube.com', category: '视频教程', lang: 'EN', source: 'YouTube', starred: 0 },
  { id: 216, title: 'YouTube Master in 30 Minutes', description: '5 real use cases', url: 'https://www.youtube.com', category: '视频教程', lang: 'EN', source: 'YouTube', starred: 0 },
  { id: 217, title: 'YouTube Install in 10 Minutes', description: 'VPS 快速部署', url: 'https://www.youtube.com', category: '视频教程', lang: 'EN', source: 'YouTube', starred: 0 },
  { id: 218, title: 'YouTube Lex Fridman Podcast', description: '3 小时深度专访', url: 'https://www.youtube.com', category: '视频教程', lang: 'EN', source: 'YouTube', starred: 0 },
  { id: 219, title: 'YouTube Secure Setup Guide', description: '安全安装和配置', url: 'https://www.youtube.com', category: '视频教程', lang: 'EN', source: 'YouTube', starred: 0 },
  { id: 220, title: 'YouTube Tech With Tim', description: '技能、语音、记忆', url: 'https://www.youtube.com', category: '视频教程', lang: 'EN', source: 'YouTube', starred: 0 },
  { id: 221, title: 'YouTube Matt Berman Use Cases', description: '真正实用的场景', url: 'https://www.youtube.com', category: '视频教程', lang: 'EN', source: 'YouTube', starred: 0 },
  { id: 222, title: 'IBM Think OpenClaw', description: 'IBM 深度分析架构创新', url: 'https://www.ibm.com', category: '深度文章', lang: 'EN', source: 'IBM', starred: 0 },
  { id: 223, title: 'Scientific American', description: '重新定义数字助手', url: 'https://www.scientificamerican.com', category: '深度文章', lang: 'EN', source: 'Scientific American', starred: 0 },
  { id: 224, title: '知乎 一文读懂 OpenClaw', description: '完整目录结构解析', url: 'https://zhuanlan.zhihu.com', category: '深度文章', lang: '中文', source: '知乎', starred: 0 },
  { id: 225, title: 'The Hacker News Malicious Skills', description: '恶意技能窃取数据', url: 'https://thehackernews.com', category: '深度文章', lang: 'EN', source: 'The Hacker News', starred: 0 },
  { id: 226, title: 'Cisco Security Nightmare', description: '安全分析', url: 'https://blogs.cisco.com', category: '深度文章', lang: 'EN', source: 'Cisco', starred: 0 },
  { id: 227, title: 'Sophos Warning Shot', description: '3 万+ 暴露实例', url: 'https://www.sophos.com', category: '深度文章', lang: 'EN', source: 'Sophos', starred: 0 },
  { id: 228, title: '飞书官方 一文搞懂 Clawd', description: 'Gateway-Node 架构解析', url: 'https://www.feishu.cn', category: '深度文章', lang: '中文', source: '飞书', starred: 0 },
  { id: 229, title: 'ClawHub 技能开发文档', description: '如何创建、发布和管理技能', url: 'https://docs.openclaw.ai', category: '技能开发', lang: 'EN', source: 'OpenClaw Docs', starred: 1 },
  { id: 230, title: 'Awesome OpenClaw Skills', description: '社区精选技能合集', url: 'https://github.com', category: '技能开发', lang: 'EN', source: 'GitHub', starred: 1 },
  { id: 231, title: 'Reddit Best OpenClaw Skills', description: '500+ 技能最佳推荐', url: 'https://www.reddit.com', category: '技能开发', lang: 'EN', source: 'Reddit', starred: 0 },
  { id: 232, title: 'OpenClaw Mega Cheatsheet', description: '150+ CLI 命令速查', url: 'https://moltfounders.com', category: '工具与插件', lang: 'EN', source: 'Molt Founders', starred: 0 },
  { id: 233, title: 'OpenClaw 汉化版', description: 'CLI + Dashboard 全中文', url: 'https://github.com', category: '工具与插件', lang: '中文', source: 'GitHub', starred: 0 },
]

// Default pages - simplified for Vercel
export const defaultPages = [
  { slug: 'day-1', lang: 'zh', title: '初识 OpenClaw' },
  { slug: 'day-2', lang: 'zh', title: '10分钟搭建助手' },
  { slug: 'day-3', lang: 'zh', title: '给助手一个灵魂' },
  { slug: 'day-4', lang: 'zh', title: '接入数字生活' },
  { slug: 'day-5', lang: 'zh', title: '解锁技能树' },
  { slug: 'day-6', lang: 'zh', title: '让助手主动工作' },
  { slug: 'day-7', lang: 'zh', title: '进阶玩法' },
]
